# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0016_auto_20180329_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='comment_date')),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aldryn_newsblog.Article')),
            ],
            options={
                'ordering': ('comment_date',),
            },
        ),
    ]
